
-- SQL Retail Sales Analysis - P1

-- CREATE TABLE
DROP TABLE IF EXISTS retail_sales;
CREATE TABLE retail_sales (
     transactions_id INT PRIMARY KEY,
     sale_date DATE,
     sale_time TIME,
     customer_id INT,
     gender VARCHAR(15),
     age INT,
     category VARCHAR(15),
     quantity INT,
     price_per_unit FLOAT,
     cogs FLOAT,
     total_sale FLOAT
);

SELECT * FROM RETAIL_SALES;

SELECT COUNT(*) FROM RETAIL_SALES;

-- DATA CLEANING

SELECT * FROM RETAIL_SALES 

WHERE 
TRANSACTIONS_ID IS NULL
OR
SALE_DATE IS NULL
OR
SALE_TIME IS NULL
OR
CUSTOMER_ID IS NULL
OR
GENDER IS NULL
OR
AGE IS NULL
OR
CATEGORY IS NULL
OR 
QUANTITY IS NULL
OR
PRICE_PER_UNIT IS NULL
OR 
COGS IS NULL
OR
TOTAL_SALE IS NULL;

DELETE FROM RETAIL_SALES

WHERE 
TRANSACTIONS_ID IS NULL
OR
SALE_DATE IS NULL
OR
SALE_TIME IS NULL
OR
CUSTOMER_ID IS NULL
OR
GENDER IS NULL
OR
AGE IS NULL
OR
CATEGORY IS NULL
OR 
QUANTITY IS NULL
OR
PRICE_PER_UNIT IS NULL
OR 
COGS IS NULL
OR
TOTAL_SALE IS NULL;

-- DATA EXPLORATION

--Q1. HOW MANY SALES WE HAVE?

SELECT COUNT(*) AS TOTAL_SALES FROM RETAIL_SALES;

--Q2. HOW MANY UNIQUE CUSTOMERS WE HAVE?

SELECT COUNT(DISTINCT CUSTOMER_ID) FROM RETAIL_SALES; 

--Q3. WHAT UNIQUE CATEGORIES DO WE HAVE?

SELECT DISTINCT CATEGORY FROM RETAIL_SALES;

-- DATA ANALYSIS & BUSINESS KEY PROBLEMS & ANSWERS.

-- MY ANALYSIS & FINDINGS

-- Q1. WRITE A SQL QUERY TO RETRIEVE ALL COLUMNS FOR SALES ON '2022-11-05'.

SELECT * FROM RETAIL_SALES WHERE SALE_DATE = '2022-11-05';

--Q2. WRITE A SQL QUERY TO RETRIEVE ALL TRANSACTIONS WHERE THE CATEGORY IS 'Clothing'
--AND THE QUANTITY SOLD IS MORE THAN OR EQUAL TO 4 IN THE MONTH OF NOV-2022.
SELECT 
  *
FROM retail_sales
WHERE 
    category = 'Clothing'
    AND 
    TO_CHAR(sale_date, 'YYYY-MM') = '2022-11'
    AND
    quantity >= 4

--Q3. WRITE A SQL QUERY TO CALCULATE THE TOTAL SALES FOR EACH CATEGORY.

SELECT CATEGORY,
SUM(TOTAL_SALE) AS NET_SALE,
COUNT(*) AS TOTAL_ORDERS
FROM RETAIL_SALES 
GROUP BY 1;

--Q4. WRITE A SQL QUERY TO FIND THE AVERAGE AGE OF CUSTOMERS WHO PURCHASED ITEMS FROM THE 
-- BEAUTY CATEGORY.

SELECT
ROUND(AVG(AGE),2) AS AVERAGE_AGE_OF_CUSTOMERS
FROM RETAIL_SALES
WHERE CATEGORY = 'Beauty';

--Q5. WRITE A SQL QUERY TO FIND ALL THE TRANSACTIONS WHERE THE TOTAL SALE IS GREATER THAN 
--1000.

SELECT * FROM RETAIL_SALES
WHERE 
TOTAL_SALE > 1000;

--Q6. WRITE A SQL QUERY TO FIND THE TOTAL NUMBER OF TRANSACTIONS MADE BY EACH GENDER IN
-- EACH CATEGORY.

SELECT CATEGORY,
GENDER,
COUNT(Transactions_id) as total_transactions 
FROM Retail_Sales
GROUP BY CATEGORY,
GENDER
ORDER BY CATEGORY;

--Q7. WRITE A SQL QUERY TO CALCULATE THE AVERAGE SALE FOR EACH MONTH.FIND OUT THE BEST 
-- SELLING MONTH IN EACH YEAR.

SELECT YEAR,
       MONTH,
	   AVERAGE_SALE
FROM 
(
SELECT 
EXTRACT (YEAR FROM SALE_DATE) AS YEAR,
EXTRACT (MONTH FROM SALE_DATE) AS MONTH,
AVG(TOTAL_SALE) AS AVERAGE_SALE,
RANK() OVER(PARTITION BY EXTRACT (YEAR FROM SALE_DATE) ORDER BY AVG(TOTAL_SALE) DESC)AS RANK
FROM RETAIL_SALES
GROUP BY 1,2
ORDER BY 1,3 DESC
)
WHERE 
RANK = 1;

--Q8. WRITE A SQL QUERY TO FIND THE TOP 5 CUSTOMERS BASED ON THE HIGHEST TOTAL SALES.

SELECT 
CUSTOMER_ID,
SUM(TOTAL_SALE) AS TOTAL_SALES
FROM RETAIL_SALES
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5

--Q9. WRITE A SQL QUERY TO FIND THE NUMBER OF UNIQUE CUSTOMERS WHO PURCHASED ITEMS 
-- FROM EACH CATEGORY.

SELECT
CATEGORY,
COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM RETAIL_SALES
GROUP BY CATEGORY;

--Q10. WRITE A SQL QUERY TO CREATE EACH SHIFT AND NUMBER OF ORDERS 
-- (EXAMPLE MORNING < 12, AFTERNOON BETWEEN 12 AND 17, EVENING > 17)

WITH HOURLY_SALE 
AS
(
SELECT *,
CASE 
WHEN EXTRACT (HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
WHEN EXTRACT (HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
ELSE 'EVENING' 
END AS SHIFT
FROM RETAIL_SALES)

SELECT 
SHIFT,
COUNT(*) AS TOTAL_ORDERS
FROM HOURLY_SALE
GROUP BY SHIFT;

-- END OF PROJECT
